# Site settings
title: Prion Alliance
description: "Prion Alliance is a 501(c)(3) non-profit devoted to funding research towards a treatment or cure for human prion disease."
# baseurl: "http://www.prionalliance.org"
url: "http://www.prionalliance.org"
username: prionalliance

# Build settings
permalink: pretty
